/**
 * Versioned educational conventions for simulator 2.1.0.
 * Values are internally consistent tuning coefficients, not universal biological constants.
 */
export const SIMULATOR_CONVENTIONS = {
  geochemicalEnergy: { none: 0, low: 0.28, moderate: 0.6, high: 0.9 },
  radiation: {
    safetyDecayMilliSvPerHour: 0.55,
  },
  carbonDioxide: {
    excessStartFraction: 0.05,
    excessScaleFraction: 0.12,
    atmospherePenalty: 0.12,
    availabilityScaleFraction: 0.012,
    availabilityExcessPenalty: 0.35,
    energyPenalty: 0.08,
  },
  atmosphere: {
    pressureIdealAtm: 1.05,
    pressureWidthAtm: 2.6,
    pressureWeight: 0.42,
    oxygenIdealAtm: 0.19,
    oxygenWidthAtm: 0.2,
    oxygenWeight: 0.45,
    nonToxicWeight: 0.13,
  },
  thermal: {
    idealC: 18,
    widthC: 58,
    meanWeight: 0.5,
    minimumWeight: 0.25,
    maximumWeight: 0.25,
    coldReferenceC: 12,
    coldScaleC: 70,
    heatReferenceC: 24,
    heatScaleC: 90,
  },
  biologicalEnergy: {
    lightWeight: 0.3,
    geochemicalWeight: 0.23,
    liquidWaterWeight: 0.18,
    humidityWeight: 0.09,
    carbonWeight: 0.1,
  },
  metabolism: {
    oxygenIdealAtm: 0.2,
    oxygenWidthAtm: 0.17,
    lowOxygenIdealAtm: 0.075,
    lowOxygenWidthAtm: 0.1,
    oxygenAvailabilityScaleAtm: 0.02,
    anaerobicEnergyFactor: 0.82,
    pathwayWeight: 0.72,
    biologicalEnergyWeight: 0.28,
    oxygenModifierWeight: 0.35,
    alternativeModifierWeight: 0.35,
  },
  physicalFitness: {
    gravityIdealG: 1,
    gravityWidthG: 1.65,
    gravityModifierScaleG: 2,
    pressureIdealAtm: 1,
    pressureWidthAtm: 5,
    pressureModifierScaleAtm: 5,
  },
  hydration: {
    liquidWaterWeight: 0.76,
    humidityWeight: 0.12,
  },
  movement: {
    base: 0.52,
    aquaticWaterWeight: 0.24,
    terrestrialWaterPenalty: 0.5,
    terrestrialWeight: 0.14,
    aerialDensityScaleKgM3: 2,
    aerialDensityWeight: 0.2,
    aerialGravityStartG: 1,
    aerialGravityScaleG: 3,
    aerialGravityPenalty: 0.18,
  },
  regions: {
    habitableScore: 0.5,
    coastal: { liquidWater: 0.34, thermal: 0.22, energy: 0.22, hydration: 0.22 },
    equatorial: {
      temperatureIdealC: 24,
      temperatureWidthC: 50,
      temperature: 0.3,
      light: 0.25,
      atmosphere: 0.2,
      radiation: 0.25,
    },
    polar: {
      temperatureIdealC: -5,
      temperatureWidthC: 44,
      temperature: 0.32,
      liquidWater: 0.18,
      radiation: 0.25,
      coldModifier: 0.45,
    },
    deepOcean: { water: 0.38, aquaticMovement: 0.2, pressure: 0.16, geochemical: 0.18, radiation: 0.08 },
    underground: { radiation: 0.18, geochemical: 0.34, pressure: 0.16, hydration: 0.16, chemosynthesis: 0.16 },
    highAltitude: { atmosphere: 0.22, radiation: 0.18, gravity: 0.14, movement: 0.18, aerialMovement: 0.2, oxygenModifier: 0.18 },
  },
  organismCompatibility: {
    gravity: 0.12,
    pressure: 0.1,
    thermal: 0.14,
    radiation: 0.13,
    hydration: 0.13,
    metabolism: 0.17,
    movement: 0.08,
    bestRegion: 0.13,
  },
  reproduction: {
    compatibility: 0.4,
    energy: 0.22,
    hydration: 0.16,
    traitModifier: 0.5,
    complexityPenalty: 0.12,
  },
  adaptability: { base: 0.18, bestRegion: 0.3 },
  populationStability: { compatibility: 0.42, reproduction: 0.28, bestRegion: 0.2, adaptability: 0.1 },
  ecosystem: { populationStability: 0.35, energy: 0.23, liquidWater: 0.16, atmosphere: 0.12, thermal: 0.14 },
  complexity: { base: 0.08, perTrait: 0.022 },
  advancedLife: { ecosystem: 0.33, metabolism: 0.17, adaptability: 0.22, complexity: 0.28 },
  population: {
    generations: 200,
    capacityBase: 1_000_000,
    minimumRegionFactor: 0.02,
    regionExponent: 1.35,
    energyBase: 0.45,
    energyWeight: 0.55,
    growthBase: 0.04,
    survivabilityGrowth: 0.24,
    reproductionGrowth: 0.38,
    adaptabilityGrowth: 0.08,
    incompatibilityMortality: 0.22,
    collapseCompatibility: 0.18,
    collapseRetention: 0.78,
    firstEventMinimumYear: 10,
    eventSpacingYears: 33,
    finalEventMaximumYear: 190,
    maximumEvents: 3,
      minimumPressureEventImpact: 0.28,
      minimumOpportunityEventImpact: 0.18,
  },
  viabilityGate: {
    minimumLiquidWater: 0.005,
    minimumBiologicalEnergy: 0.06,
    minimumThermalStability: 0.05,
    minimumRadiationSafety: 0.04,
  },
  advancedLifeQualification: { advancedLife: 0.67, ecosystem: 0.55, finalPopulation: 1_000 },
  outcomes: {
    extinctionCompatibility: 0.15,
    temporaryPopulationFraction: 0.5,
    refugeCompatibility: 0.48,
    advancedLife: 0.78,
    multicellularEcosystem: 0.66,
    multicellularStability: 0.6,
    dominanceCapacityFraction: 0.94,
    dominanceStability: 0.58,
    expandingPopulationMultiplier: 3,
  },
} as const;
